"use client";

import { useState } from "react";
import { Download, FileText, Loader2 } from "lucide-react";
import { TissueSection } from "@/lib/data/histologyData";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface StudyGuideExporterProps {
  section: TissueSection;
}

export default function StudyGuideExporter({ section }: StudyGuideExporterProps) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const doc = new jsPDF("p", "mm", "a4");
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Header
      doc.setFillColor(2, 6, 23); // bg-[#020617]
      doc.rect(0, 0, pageWidth, 40, "F");
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text("HISTOPRO STUDY GUIDE", 15, 20);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Specimen Identification Card", 15, 30);
      
      // Specimen Title
      doc.setTextColor(79, 70, 229); // indigo-600
      doc.setFontSize(28);
      doc.text(section.title.toUpperCase(), 15, 60);
      
      // Description
      doc.setTextColor(60, 60, 60);
      doc.setFontSize(12);
      const splitDesc = doc.splitTextToSize(section.description, pageWidth - 30);
      doc.text(splitDesc, 15, 75);
      
      // Identification Points
      let yPos = 100;
      doc.setFillColor(243, 244, 246);
      doc.rect(15, yPos - 5, pageWidth - 30, 10, "F");
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(14);
      doc.text("DIAGNOSTIC CRITERIA", 20, yPos + 2);
      
      yPos += 15;
      section.practicalTips?.forEach((tip, index) => {
        doc.setFontSize(11);
        const splitTip = doc.splitTextToSize(`• ${tip}`, pageWidth - 40);
        doc.text(splitTip, 20, yPos);
        yPos += splitTip.length * 7;
      });
      
      // Confusion Warning
      if (section.confusionWarning) {
        yPos += 10;
        doc.setFillColor(254, 242, 242);
        doc.rect(15, yPos, pageWidth - 30, 25, "F");
        doc.setTextColor(153, 27, 27);
        doc.setFontSize(12);
        doc.text("CONFUSION WARNING:", 20, yPos + 10);
        doc.setFontSize(10);
        const splitWarning = doc.splitTextToSize(section.confusionWarning, pageWidth - 40);
        doc.text(splitWarning, 20, yPos + 18);
      }
      
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by HistoPro Engine - ${new Date().toLocaleDateString()}`, 15, 285);

      doc.save(`HistoPro_${section.title.replace(/\s+/g, "_")}.pdf`);
    } catch (error) {
      console.error("Export failed:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={isExporting}
      className="flex items-center gap-2 px-6 py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl text-xs font-black uppercase tracking-widest text-slate-400 hover:text-white transition-all disabled:opacity-50"
    >
      {isExporting ? (
        <>
          <Loader2 size={16} className="animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <FileText size={16} />
          Download Study Card (PDF)
        </>
      )}
    </button>
  );
}
